opengovsg/isomer-build

overrides/netlify.toml
Duplicate of https://github.com/opengovsg/isomer-build/pull/30 to master
=> Fix: add accounts.google.com to csp

overrides/netlify.toml
Adds the sha for the inline script required for GTM to work to our script-src.
=> Feat/add inline script for GTM

overrides/customHttp.yml
Duplicate of https://github.com/opengovsg/isomer-build/pull/38 for amplify
=> Feat/add inline script for GTM amplify

overrides/customHttp.yml
Dupe of https://github.com/opengovsg/isomer-build/pull/40 to amplify
=> Add wizgov to csp (amplify)

overrides/customHttp.yml
=> Allow sgid (amplify)

overrides/netlify.toml
Updates whitelist for wizgov widget's changed endpoint
=> chore: update wizgov endpoint (netlify)

overrides/customHttp.yml
=> Update wizgov endpoint (amplify)

overrides/customHttp.yml
=> feat/askjamie (amplify)

overrides/_config-override.yml
Duplicate of #52 but for Netlify.
=> feat(sass): compress SASS styles

overrides/netlify.toml
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> Add https://vimeo.com to frame-src

overrides/customHttp.yml
This PR adds additional sources for script-src which are required for our new GTM tag to work. To be reviewed in conjunction with PR [#402](https://github.com/isomerpages/isomerpages-template/pull/402) in the isomerpages-template repo.
=> feat/add script-src for gtm load time

overrides/netlify.toml
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> chore: add *.data.gov.sg to frame-src (netlify)

overrides/customHttp.yml
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> chore: add *.data.gov.sg to frame-src

overrides/customHttp.yml
=> fix(csp): allow lighten csp rules

build.sh
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> chore(amplify): lock-deps

overrides/customHttp.yml
https://opengovproducts.slack.com/archives/CK68JNFHR/p1719904475582179?thread_ts=1719795602.001499&cid=CK68JNFHR
=> fix(sabio): add csp to style and connect src

overrides/netlify.toml
[For context](https://opengovproducts.slack.com/archives/CK68JNFHR/p1719904475582179?thread_ts=1719795602.001499&cid=CK68JNFHR)
=> fix(sabio): add to style and connect src

build.sh, overrides/netlify.toml
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> feat: update referrer policy

overrides/customHttp.yml
add wizgov cos customs needs this script
=> chore(wizgov): add wizgov for customs script

overrides/netlify.toml
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> chore: update csp for netlify

overrides/netlify.toml
=> chore: add more whitelists for WizGov

overrides/netlify.toml
=> chore: whitelist more WizGov scripts
